M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 December 25, Sunday 16:24:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-25T16:24:32+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.988
%
G90
G05
T1
X128.905Y-56.039
X128.905Y-66.199
X128.905Y-75.089
X128.905Y-85.249
T2
X128.905Y-61.119
X128.905Y-80.169
T0
M30
